version: 2

jobs:
    build:
        working_directory: /go/src/github.com/turnerlabs/cstore
        docker:
            - image: circleci/golang:1.9
        steps:
            - checkout

            - run: curl https://glide.sh/get | sh
            - run: glide install
            
            - run: go test ./... 

            - run: go get github.com/mitchellh/gox
            - run:
                name: Build App
                command: |
                    if [ -z $CIRCLE_TAG ] 
                    then
                        gox -os="linux" -os="windows" -ldflags "-X main.version=v0.0.0-notag.$CIRCLE_BUILD_NUM" -output "artifacts/cstore_{{.OS}}_{{.Arch}}"
                    else
                        gox -os="linux" -os="windows" -ldflags "-X main.version=$CIRCLE_TAG.$CIRCLE_BUILD_NUM" -output "artifacts/cstore_{{.OS}}_{{.Arch}}"
                    fi  

            - persist_to_workspace:
                root: .
                paths:
                    - artifacts/*

    publish-github-release:
        working_directory: /go/src/github.com/turnerlabs/cstore
        docker:
            - image: circleci/golang:1.9
        steps:
            - attach_workspace:
                at: /go/src/github.com/turnerlabs/cstore
            - run:
                name: "Publish Release on GitHub"
                command: |
                    go get github.com/tcnksm/ghr
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} /go/src/github.com/turnerlabs/cstore/artifacts

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*-[a-z]*$/
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*-[a-z]*$/
            branches:
              ignore: /.*/
          
