name: Go
# on: [push]
on:
  push:
    tags:
    - '^v[0-9]+(\.[0-9]+)*-[a-z]*$'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
     
    - name: Run tests
      run: go test ./... 

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and Publish Code
      uses: ./.github/shell
      env:
        #TAG: v1.0.0-actions
        GOROOT: /usr/local/go
      with:
        args: |
          cd cli
          gox -os='linux' -os='windows' -ldflags '-X main.version=${GITHUB_REF/refs\/tags\//}.$GITHUB_RUN_NUMBER' -output 'artifacts/cstore_{{.OS}}_{{.Arch}}'
          ghr -t '${{ secrets.GITHUB_TOKEN }}' -u turnerlabs -r cstore -c $GITHUB_SHA -delete ${GITHUB_REF/refs\/tags\//} artifacts
        
